# aqui se crean las imagenes de docker para cada microservicio
# son llamados en el docker-compose.yml para crear los contenedores
# puedes crear varios microservicios y cada uno tendra su propia imagen de docker
# cada microservicio tiene su propio Dockerfile y se construye su imagen de docker